[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# PostgreSQL Database Configuration
[[services]]
name = "partnerkin-db"

[services.variables]
DB_TYPE = "postgresql"

[services.source]
type = "postgresql"

# Environment variables for PostgreSQL
[env]
DB_TYPE = "postgresql"