services:
  # Web service for Express server and bot (Webhook mode)
  - type: web
    name: partnerkin-bot
    runtime: node
    repo: https://github.com/TheX6/partnerkin_super_bot
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: DB_TYPE
        value: postgresql
      - key: DB_HOST
        fromDatabase:
          name: partnerkin-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: partnerkin-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: partnerkin-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: partnerkin-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: partnerkin-db
          property: password
      - key: DB_SSL
        value: "true"
      - key: RENDER
        value: true
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: partnerkin-bot
          property: url
  # PostgreSQL Database Service
  - type: pserv
    name: partnerkin-db
    runtime: postgres
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /
    databases:
      - name: partnerkin-db
    autoDeploy: true
    healthCheckPath: /health
