name: CI/CD Pipeline

on:
  push:
    branches:
      - nightly # Запускаем при коммитах в nightly
  pull_request:
    branches:
      - nightly # Запускаем при пулл-реквестах в nightly
  push:
    branches:
      - main

jobs:
  check_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Установка Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Установка зависимостей
        run: npm ci
      - name: Проверка синтаксиса (например)
        run: echo "Код проверен, ошибок нет" # Замените это на реальную проверку, если есть.

  deploy_to_staging:
    needs: check_code
    if: github.ref == 'refs/heads/nightly'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Развертывание на тестовом сервере
        run: |
          echo "Развертываем на тестовом сервере..."

  deploy_to_production:
    needs: check_code
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Развертывание на продакшене
        run: |
          echo "Развертываем на продакшене!"